### PR TITLE
Fhir docs

### PR DESCRIPTION
**Pull request by spencer-skylight**
Create documentation around performing FHIR-related queries and authentication.

### CODE REVIEW

**Review by bamader — APPROVED** [review]
Seems legit!

**Review by DanPaseltiner — COMMENTED** [review]
In general I thought we were trying to keep this type of documentation in the private repo. I could be wrong. Might be worth a conversation before merging.

**Comment by spencer-skylight** [comment]
@DanPaseltiner that makes sense... I won't be on the standup tomorrow to discuss unfortunately, but perhaps the team could discuss and I can update accordingly.

**Comment by spencer-skylight** [comment]
Moved to: https://github.com/usds/PRIME-PHDI-Internal/pull/17

**Pull request closed without merging**
